apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-imagenet-resnet50-web-single
  labels:
    app: api-imagenet-resnet50-web-single
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: api-imagenet-resnet50-web-single
  replicas: 1
  template:
    metadata:
      labels:
        app: api-imagenet-resnet50-web-single
      name: api-imagenet-resnet50-web-single
    spec:
      containers:
      - name: api-imagenet-resnet50-web-single
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_api_imagenet_resnet50:latest
        command: ["./run_api.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: imagenet_resnet50.yaml
        - name: GUNICORN_UVICORN
          value: GUNICORN
        - name: WORKERS
          value: "4"
        - name: APP_NAME
          value: "app.apps.app_web_single_image"
        - name: PORT
          value: "8891"
        - name: PROFILE
          value: "0"
        ports:
        - containerPort: 8891

---

apiVersion: v1
kind: Service
metadata:
  name: api-imagenet-resnet50-web-single
  labels:
    app: api-imagenet-resnet50-web-single
  namespace: serving-pattern
spec:
  ports:
  - port: 8891
    protocol: TCP
  selector:
    app: api-imagenet-resnet50-web-single
