apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-iris-svc
  labels:
    app: backend-iris-svc
  namespace: serving-pattern
spec:
  selector:
    matchLabels:
      app: backend-iris-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-iris-svc
      name: backend-iris-svc
    spec:
      containers:
      - name: backend-iris-svc
        image: gcr.io/newagent-16e99/github.com/shibuiwilliam/ml-system-in-action/serving_patterns_backend_iris:latest
        command: ["./run_backend.sh"]
        env:
        - name: PLATFORM
          value: kubernetes
        - name: CACHE_HOST
          value: redis.serving-pattern.svc.cluster.local
        - name: MODEL_INTERFACE
          value: iris_svc_onnx_runtime.yaml
        - name: NUM_PROCS
          value: "4"
        - name: APP_NAME
          value: "app.backend.prediction_batch"
        - name: PROFILE
          value: "0"
        - name: QUEUE_NAME
          value: svc_api_queue
        resources:
          limits:
            cpu: "2"
            memory: "2000Mi"
          requests:
            cpu: "2"
            memory: "2000Mi"
